spring:
  datasource:
    url: jdbc:postgresql://localhost:1234/peaksoftdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect